project:
  type: website
  resources:
    - "icons/"

execute:
  freeze: auto
  echo: true
  eval: true
  collapse: false

website:
  title: "DATA2"
  navbar:
    background: primary
    search: true
    right:
      - href: https://canvas.ku.edu/courses/185369
        icon: mortarboard
        text: "Canvas"
      - href: https://ku.simplesyllabus.com/api2/doc-pdf/we1q6q8u0/Spring-2026-ECON-399-50843-Data-2%3A-Foundations-of-Data-Science.pdf?locale=en-US
        icon: file-text
        text: "Syllabus"
      - href: schedule.qmd
        icon: calendar
        text: "Schedule"
      - text: Unit A
        menu:
          - icon: compass
            text: "Week 01: Orient"
            href: A/01/index.html
          - icon: rocket-takeoff
            text: "Week 02: Start"
            href: A/02/index.html
          - icon: code-square
            text: "Week 03: Program"
            href: A/03/index.html
          - icon: table
            text: "Week 04: Wrangle"
            href: A/04/index.html
          - icon: graph-up-arrow
            text: "Week 05: Visualize"
            href: A/05/index.html
          - icon: chat-quote
            text: "Week 06: Communicate"
            href: A/06/index.html
          - icon: people
            text: "Week 07: Collaborate"
            href: A/07/index.html
          - icon: easel2
            text: "Week 08: Present"
            href: A/08/index.html
      - text: Unit B
        menu:
          - icon: balloon
            text: "Week 09: Rest"
            href: B/10/index.html
          - icon: calculator
            text: "Week 10: Infer"
            href: B/10/index.html
          - icon: shuffle
            text: "Week 11: Reshape"
            href: B/11/index.html
          - icon: body-text
            text: "Week 12: Wrangle"
            href: B/12/index.html
          - icon: brush
            text: "Week 13: Visualize"
            href: B/13/index.html
          - icon: arrow-repeat
            text: "Week 14: Program"
            href: B/14/index.html
          - icon: people
            text: "Week 15: Collaborate"
            href: B/15/index.html
          - icon: easel2
            text: "Week 16: Present"
            href: B/16/index.html
  page-footer: "Copyright 2026 &copy; Jeffrey Girard"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
