---
title: "Foundations of Data Science"
toc: false
email-obfuscation: javascript
---

Data science empowers its users to provide data-drive solutions to problems and questions in the world. This course provides foundational skill and knowledge behind this power. This knowledge and skill includes learning to formulate effective questions to answer with data, computer programming, data management and wrangling, exploratory data analysis and visualization, statistical inference and prediction, data-driven decision making, and communication.

### Learning Outcomes

At the conclusion of this course, students will be able to:

- Explain the pros and cons of R as a platform for data science
- Implement a data science workflow using RStudio Projects and Quarto
- Accomplish basic and intermediate programming tasks using R and tidyverse
- Accomplish basic and intermediate data wrangling tasks using dplyr and tidyr
- Accomplish basic and intermediate data visualization tasks using ggplot2
- Customize Quarto reports and ggplots to enhance communication
- Collaborate with a group to plan and execute a data science project

### Instructor

- [Dr. Jeffrey Girard](mailto:jmgirard@ku.edu), Instructor
- [Dasha Yermol](mailto:dayermol@ku.edu), Teaching Assistant

### Class Time and Location

- MWF 10:00 AM - 10:50 AM in FR 547

### Update Progress

Below, I will track my progress updating this website week-by-week.

:::{.columns}
:::{.column width="50%"}
- [x] Week 01
- [x] Week 02
- [x] Week 03
- [ ] Week 04
- [ ] Week 05
- [ ] Week 06
- [ ] Week 07
- [ ] Week 08
:::
:::{.column width="50%"}
- [ ] Week 09
- [ ] Week 10
- [ ] Week 11
- [ ] Week 12
- [ ] Week 13
- [ ] Week 14
- [ ] Week 15
- [ ] Week 16
:::
:::
