---
title: "Week 05: Visualize"
execute:
  echo: true
  eval: true
---

```{r}
#| include: false
#| label: setup

library(here)
source(here("_common.R"))

knitr::opts_chunk$set(collapse = TRUE)
```

:::{.callout-caution title="Work in Progress"}
This page is still under development.
:::

## [05a] Graphics / Scatterplots

### Topics
- Learn the principles that govern data visualization
- Create and save scatterplots using `ggplot()` and `ggsave()`

### Readings
- R4DS (2E) Section 1.1: [Introductions](https://r4ds.hadley.nz/data-visualize.html#introduction){target="_blank"}
- R4DS (2E) Section 1.2: [First Steps](https://r4ds.hadley.nz/data-visualize.html#first-steps){target="_blank"}
- R4DS (2E) Section 1.3: [ggplot2 calls](https://r4ds.hadley.nz/data-visualize.html#sec-ggplot2-calls){target="_blank"}
- R4DS (2E) Section 1.6: [Saving your plots](https://r4ds.hadley.nz/data-visualize.html#sec-ggsave){target="_blank"}

### Slides
```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[05a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and then press 'F' on your keyboard to view the slides full screen.
:::

### Practice



## [05b] Distributions / Relationships

### Topics
- Visualize the distribution of a single variable
- Visualize relationships between several variables

### Readings
- R4DS (2E) Section 1.4: [Visualizing distributions](https://r4ds.hadley.nz/data-transform.html#introduction){target="_blank"}
- R4DS (2E) Section 1.5: [Visualizing relationships](https://r4ds.hadley.nz/data-visualize.html#visualizing-distributions){target="_blank"}

### Slides
```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[05b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and then press 'F' on your keyboard to view the slides full screen.
:::

### Practice



## [05c] Aesthetics / Geometrics

### Topics
- Learn when to "set" versus "map" an aesthetic value
- Combine layers of geometrics objects (points and smooths)

### Readings
- R4DS (2E) Section 9.2: [Aesthetic mappings](https://r4ds.hadley.nz/layers.html#aesthetic-mappings){target="_blank"}
- R4DS (2E) Section 9.3: [Geometric objects](https://r4ds.hadley.nz/layers.html#sec-geometric-objects){target="_blank"}

### Slides
```{=html}
<iframe class="slide-deck" src="c_Slides.html" title="[05c] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and then press 'F' on your keyboard to view the slides full screen.
:::

### Practice


<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../04/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 04</a>

  <a href="../06/index.html" class="btn btn-primary" role="button">Week 06&nbsp;&nbsp;&raquo;</a>
</div>
```
