---
title: "Week 4: Wrangle"
format:
  html:
    page-layout: full
---

## [04a] Tidy Data

### Topics

- Principles
- Tibbles
- Data Files

### Slides

<iframe class="slide-deck" src="./Presentations/04a_Slides.html" title="[04a] Presentation">
</iframe>

[Click here to view the slides in their own window.](./Presentations/04a_Slides.html)

### Recording

<iframe id="kmsembed-1_l15p72tz" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_l15p72tz/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [04a]"></iframe>

### Data Files

- <a href="../data/kaggle_cereal.csv" download="kaggle_cereal.csv">kaggle_cereal.csv</a>

### Activity

- [Activity \[04a\]](./Activities/04a_Activity.html)


## [04b] dplyr Basics

### Topics

- Column verbs
- Row verbs
- Pipelines

### Slides

<iframe class="slide-deck" src="./Presentations/04b_Slides.html" title="[04b] Presentation">
</iframe>

### Recording

<iframe id="kmsembed-1_m1o3yk9o" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_m1o3yk9o/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [04b]"></iframe>

### Data Files

- <a href="../data/kaggle_cereal.csv" download="kaggle_cereal.csv">kaggle_cereal.csv</a>

### Activity

- [Activity \[04b\]](./Activities/04b_Activity.html)

## Week 4 Assignment

### Instructions

- [Week 4 Assignment](./Assignments/04_Assignment.html)

### Data Files

- <a href="../data/example4.csv" download="example4.csv">example4.csv</a>
