---
title: "Week 3: Program"
format:
  html:
    page-layout: full
---

## [03a] Basic Programming

### Topics

- Assignment
- Naming
- Functions

### Slides

<iframe class="slide-deck" src="./Presentations/03a_Slides.html" title="[03a] Presentation">
</iframe>

[Click here to view the slides in their own window.](./Presentations/03a_Slides.html)

### Recording

<iframe id="kmsembed-1_6135tjg4" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_6135tjg4/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [03a]"></iframe>

### Activity

- [Activity \[03a\]](./Activities/03a_Activity.html)

## [03b] More Programming

### Topics

- Vectors
- Strings
- Packages

### Slides

<iframe class="slide-deck" src="./Presentations/03b_Slides.html" title="[03b] Presentation">
</iframe>

### Recording

<iframe id="kmsembed-1_sy7dg3ck" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_sy7dg3ck/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [03b]"></iframe>

### Activity

- [Activity \[03b\]](./Activities/03b_Activity.html)

## Week 3 Assignment

### Instructions

- [Week 3 Assignment](./Assignments/03_Assignment.html)
