---
title: "Week 13: Visualize"
execute:
  echo: true
  eval: true
---

```{r}
#| include: false
#| label: setup

library(here)
source(here("_common.R"))

knitr::opts_chunk$set(collapse = TRUE)
```

## [13a] Positions

### Topics
- A
- B
- C

### Readings
- R4DS (2E) Section 9.4: [Facets](https://r4ds.hadley.nz/layers.html#facets){target="_blank"}
- R4DS (2E) Section 9.6: [Position Adjustments](https://r4ds.hadley.nz/layers.html#position-adjustments){target="_blank"}


### Slides
```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[13a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice
TBA

## [13b] Coordinates

### Topics
- A
- B
- C

### Readings
- R4DS (2E) Section 9.5: [Statistical Transformations](https://r4ds.hadley.nz/layers.html#statistical-transformations){target="_blank"}
- R4DS (2E) Section 9.7: [Coordinate Systems](https://r4ds.hadley.nz/layers.html#coordinate-systems){target="_blank"}
- EGDA (3E) Chapter 6: [Maps](https://ggplot2-book.org/maps.html){target="_blank"}

### Slides
```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[13b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice
TBA

## [13c] Themes

### Topics
- A
- B
- C

### Readings
- R4DS (2E) Section 11.5: [Themes](https://r4ds.hadley.nz/communication.html#sec-themes){target="_blank"}
- R4DS (2E) Section 11.6: [Layout](https://r4ds.hadley.nz/communication.html#layout){target="_blank"}

### Slides
```{=html}
<iframe class="slide-deck" src="c_Slides.html" title="[13c] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice
TBA

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../12/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 12</a>

  <a href="../14/index.html" class="btn btn-primary" role="button">Week 14&nbsp;&nbsp;&raquo;</a>
</div>
```
