---
title: "Week 14: Program"
execute:
  echo: true
  eval: true
---

```{r}
#| include: false
#| label: setup

library(here)
source(here("_common.R"))

knitr::opts_chunk$set(collapse = TRUE)
```

## [13a] Conditionals

### Topics
- A
- B
- C

### Readings
- R4DS (2E) Chapter 12: [Logical vectors](https://r4ds.hadley.nz/logicals.html){target="_blank"}

### Slides
```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[14a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice


## [14b] Functions

### Topics
- A
- B
- C

### Readings
- R4DS (2E) Chapter 25: [Functions](https://r4ds.hadley.nz/functions.html){target="_blank"}


### Slides
```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[14b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice



## [14c] Iteration

### Topics
- A
- B
- C

### Readings
- R4DS (2E) Chapter 26: [Iteration](https://r4ds.hadley.nz/iteration.html){target="_blank"}


### Slides
```{=html}
<iframe class="slide-deck" src="c_Slides.html" title="[14c] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice



<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../12/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 12</a>

  <a href="../14/index.html" class="btn btn-primary" role="button">Week 14&nbsp;&nbsp;&raquo;</a>
</div>
```
