---
title: "Week 11: Wrangle"
format:
  html:
    page-layout: full
---

## [11a] Reshaping Data

### Topics

- Separate and Unite
- Pivot Longer
- Pivot Wider

### Slides

<iframe class="slide-deck" src="./Presentations/11a_Slides.html" title="[11a] Presentation">
</iframe>

[Click here to view the slides in their own window.](./Presentations/11a_Slides.html)

### Recording

<iframe id="kmsembed-1_jbrx8twl" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_jbrx8twl/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [11a]"></iframe>

### Activity

- [Activity \[11a\]](./Activities/11a_Activity.html)


## [11b] Joining Data

### Topics

- Relational Data
- Basic Joins
- dplyr Joins

### Slides

<iframe class="slide-deck" src="./Presentations/11b_Slides.html" title="[11b] Presentation">
</iframe>

### Recording

<iframe id="kmsembed-1_qqfmng96" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_qqfmng96/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [11b]"></iframe>

### Activity

- [Activity \[11b\]](./Activities/11b_Activity.html)


## Week 11 Assignment

### Instructions

- [Week 11 Assignment](./Assignments/11_Assignment.html)

### Data Files

- <a href="../data/couples.rds" download="couples.rds">couples.rds</a>
