---
title: "Week 12: Visualize"
format:
  html:
    page-layout: full
---

## [12a] Advanced Elements

### Topics

- Faceting
- Positions
- Stat Summary

### Slides

<iframe class="slide-deck" src="./Presentations/12a_Slides.html" title="[12a] Presentation">
</iframe>

[Click here to view the slides in their own window.](./Presentations/12a_Slides.html)

### Recording

<iframe id="kmsembed-1_v4x4sqmj" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_v4x4sqmj/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [12a]"></iframe>

### Activity

- [Activity \[12a\]](./Activities/12a_Activity.html)


## [12b] Advanced Elements

### Topics

- Highlighting
- Layouts
- Exporting

### Slides

<iframe class="slide-deck" src="./Presentations/12b_Slides.html" title="[12b] Presentation">
</iframe>

### Recording

<iframe id="kmsembed-1_cn7do6nb" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_cn7do6nb/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [12b]"></iframe>

### Activity

- [Activity \[12b\]](./Activities/12b_Activity.html)


## Week 12 Assignment

### Instructions

- [Week 12 Assignment](./Assignments/12_Assignment.html)
