---
title: "Week 13: Program"
format:
  html:
    page-layout: full
---

## [13a] Special Data Types

### Topics

- Strings
- Factors
- Dates and Times

### Slides

<iframe class="slide-deck" src="./Presentations/13a_Slides.html" title="[13a] Presentation">
</iframe>

[Click here to view the slides in their own window.](./Presentations/13a_Slides.html)

### Recording

<iframe id="kmsembed-1_zczblk9x" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_zczblk9x/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [13a]"></iframe>

### Activity

- [Activity \[13a\]](./Activities/13a_Activity.html)


## [13b] Automation

### Topics

- Control Flow
- Custom Functions
- Basic Iteration

### Slides

<iframe class="slide-deck" src="./Presentations/13b_Slides.html" title="[13b] Presentation">
</iframe>

### Recording

<iframe id="kmsembed-1_0f5c0i79" width="400" height="285" src="https://mediahub.ku.edu/embed/secure/iframe/entryId/1_0f5c0i79/uiConfId/45147491/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="399/800 Lecture [13b]"></iframe>

### Data Files

To follow along with the iteration live coding, save these three files into a folder called "data" inside your project folder:

- <a href="../data/pid_001.csv" download="pid_001.csv">pid_001.csv</a>
- <a href="../data/pid_002.csv" download="pid_002.csv">pid_002.csv</a>
- <a href="../data/pid_003.csv" download="pid_003.csv">pid_003.csv</a>

### Activity

- [Activity \[13b\]](./Activities/13b_Activity.html)


## Week 13 Assignment

### Instructions

- [Week 13 Assignment](./Assignments/13_Assignment.html)

### Data Files

- <a href="../data/movies2021.csv" download="movies2021.csv">movies2021.csv</a>
